# 10-ignores.sh

# TODO pacman

IgnorePath '/etc/pacman.conf'             # Pacman package manager configuration file
IgnorePath '/etc/pacman.d/*mirrorlist*'   # Pacman package manager mirrorfiles

# TODO users

IgnorePath '/etc/fstab'                   # Static information about the filesystems (genfstab)
IgnorePath '/etc/*shadow*'                # Shadowed password file contains the password information and optional aging information
IgnorePath '/etc/group*'                  # User group file
IgnorePath '/etc/passwd*'                 # The password file with user account information
IgnorePath '/etc/subgid*'                 # Configuration for subordinate group ids
IgnorePath '/etc/subuid*'                 # Configuration for subordinate user ids

# /boot

IgnorePath '/boot/efi/*'                  # ESP (grub-install)
IgnorePath '/boot/grub/*'                 # Grub config (grub-mkconfig)
IgnorePath '/boot/initr*'                 # initramfs image (mkinitcpio)
IgnorePath '/boot/vmlinuz*'               # kernel image

# /etc

IgnorePath '/etc/.pwd.lock'               # passwd and shadow lock file
IgnorePath '/etc/.updated'                # Created by systemd-update-done to hold a timestamp of the time this directory was updated
IgnorePath '/etc/ca-certificates/*'       # CA certificates
IgnorePath '/etc/ld.so.cache'             # Libraries cache file (ldconfig)
IgnorePath '/etc/machine-id'              # Local machine ID configuration file that is set during installation or boot
IgnorePath '/etc/mkinitcpio.d/*'          # Presets for mkinitcpio generated by a pacman hook every time a kernel is installed or upgraded
IgnorePath '/etc/os-release'              # Operating system identification
IgnorePath '/etc/pacman.d/gnupg/*'        # Pacman GnuPG keys (pacman-key --init)
IgnorePath '/etc/resolv.conf'             # Generated by NetworkManager
IgnorePath '/etc/ssl/certs/*'             # Certificates

# /lost+found

IgnorePath '/lost+found'                  # Contains files that have been deleted or lost in a disk operation

# /usr

IgnorePath '/usr/bin/groupmems'           # Permission change
IgnorePath '/usr/lib/modules/*/build'     # Kernel modules
IgnorePath '/usr/lib/modules/*/kernel'    # Kernel modules
IgnorePath '/usr/lib/modules/*/modules.*' # Kernel modules
IgnorePath '/usr/lib/udev/hwdb.bin'       # Hardware Database
IgnorePath '/usr/lib/utempter/utempter'   # Permission change

# others

IgnorePath '/var/*'                       # Persistent, variable system data
